version: "3.7"
services:
  backend:
    build: spring-boot-backend
    ports:
      - 8080:8080
  frontend:
    # build: react-frontend
    # ports:
    #   - 80:80
    build:
      context: react-frontend
      target: development
    ports:
      - 3000:3000
    # both src and node_modules must be synchronized in order for hot reloading to work
    volumes:
      - ./react-frontend/src:/app/src
      - ./react-frontend/node_modules:/app/node_modules
    # additionally, this env var is needed so that the filesystem in the container is actually watched for new changes
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
